//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimsteMens.Services.SlimsteAdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GameDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.RoundTypeDto> RoundsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartingSecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Team1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Team2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Team3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.RoundTypeDto> Rounds {
            get {
                return this.RoundsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundsField, value) != true)) {
                    this.RoundsField = value;
                    this.RaisePropertyChanged("Rounds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartingSeconds {
            get {
                return this.StartingSecondsField;
            }
            set {
                if ((this.StartingSecondsField.Equals(value) != true)) {
                    this.StartingSecondsField = value;
                    this.RaisePropertyChanged("StartingSeconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team1 {
            get {
                return this.Team1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Team1Field, value) != true)) {
                    this.Team1Field = value;
                    this.RaisePropertyChanged("Team1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team2 {
            get {
                return this.Team2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Team2Field, value) != true)) {
                    this.Team2Field = value;
                    this.RaisePropertyChanged("Team2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team3 {
            get {
                return this.Team3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Team3Field, value) != true)) {
                    this.Team3Field = value;
                    this.RaisePropertyChanged("Team3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoundTypeDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    public enum RoundTypeDto : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreeSixNine = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Puzzle = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lists = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gallery = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Video = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finale = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetGameDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResetGameDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Team1SecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Team2SecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Team3SecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SlimsteMens.Services.SlimsteAdminService.TurnTypeDto TurnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Team1Seconds {
            get {
                return this.Team1SecondsField;
            }
            set {
                if ((this.Team1SecondsField.Equals(value) != true)) {
                    this.Team1SecondsField = value;
                    this.RaisePropertyChanged("Team1Seconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Team2Seconds {
            get {
                return this.Team2SecondsField;
            }
            set {
                if ((this.Team2SecondsField.Equals(value) != true)) {
                    this.Team2SecondsField = value;
                    this.RaisePropertyChanged("Team2Seconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Team3Seconds {
            get {
                return this.Team3SecondsField;
            }
            set {
                if ((this.Team3SecondsField.Equals(value) != true)) {
                    this.Team3SecondsField = value;
                    this.RaisePropertyChanged("Team3Seconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SlimsteMens.Services.SlimsteAdminService.TurnTypeDto Turn {
            get {
                return this.TurnField;
            }
            set {
                if ((this.TurnField.Equals(value) != true)) {
                    this.TurnField = value;
                    this.RaisePropertyChanged("Turn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnTypeDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    public enum TurnTypeDto : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Team1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Team2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Team3 = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThreeSixNineQuestionDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ThreeSixNineQuestionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuzzleQuestionDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PuzzleQuestionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Hint1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Hint2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Hint3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Hint4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hint1 {
            get {
                return this.Hint1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Hint1Field, value) != true)) {
                    this.Hint1Field = value;
                    this.RaisePropertyChanged("Hint1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hint2 {
            get {
                return this.Hint2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Hint2Field, value) != true)) {
                    this.Hint2Field = value;
                    this.RaisePropertyChanged("Hint2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hint3 {
            get {
                return this.Hint3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Hint3Field, value) != true)) {
                    this.Hint3Field = value;
                    this.RaisePropertyChanged("Hint3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hint4 {
            get {
                return this.Hint4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Hint4Field, value) != true)) {
                    this.Hint4Field = value;
                    this.RaisePropertyChanged("Hint4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GalleryDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GalleryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.GalleryQuestionDto> QuestionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.GalleryQuestionDto> Questions {
            get {
                return this.QuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionsField, value) != true)) {
                    this.QuestionsField = value;
                    this.RaisePropertyChanged("Questions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GalleryQuestionDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GalleryQuestionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoAnswerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PhotoAnswer {
            get {
                return this.PhotoAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoAnswerField, value) != true)) {
                    this.PhotoAnswerField = value;
                    this.RaisePropertyChanged("PhotoAnswer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VideoDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class VideoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer1 {
            get {
                return this.Answer1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer1Field, value) != true)) {
                    this.Answer1Field = value;
                    this.RaisePropertyChanged("Answer1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer2 {
            get {
                return this.Answer2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer2Field, value) != true)) {
                    this.Answer2Field = value;
                    this.RaisePropertyChanged("Answer2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer3 {
            get {
                return this.Answer3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer3Field, value) != true)) {
                    this.Answer3Field = value;
                    this.RaisePropertyChanged("Answer3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer4 {
            get {
                return this.Answer4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer4Field, value) != true)) {
                    this.Answer4Field = value;
                    this.RaisePropertyChanged("Answer4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer5 {
            get {
                return this.Answer5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer5Field, value) != true)) {
                    this.Answer5Field = value;
                    this.RaisePropertyChanged("Answer5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoPath {
            get {
                return this.VideoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoPathField, value) != true)) {
                    this.VideoPathField = value;
                    this.RaisePropertyChanged("VideoPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinaleTurnTypeDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    public enum FinaleTurnTypeDto : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Team1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Team2 = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinaleQuestionDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class FinaleQuestionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer1 {
            get {
                return this.Answer1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer1Field, value) != true)) {
                    this.Answer1Field = value;
                    this.RaisePropertyChanged("Answer1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer2 {
            get {
                return this.Answer2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer2Field, value) != true)) {
                    this.Answer2Field = value;
                    this.RaisePropertyChanged("Answer2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer3 {
            get {
                return this.Answer3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer3Field, value) != true)) {
                    this.Answer3Field = value;
                    this.RaisePropertyChanged("Answer3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer4 {
            get {
                return this.Answer4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer4Field, value) != true)) {
                    this.Answer4Field = value;
                    this.RaisePropertyChanged("Answer4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer5 {
            get {
                return this.Answer5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer5Field, value) != true)) {
                    this.Answer5Field = value;
                    this.RaisePropertyChanged("Answer5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Played {
            get {
                return this.PlayedField;
            }
            set {
                if ((this.PlayedField.Equals(value) != true)) {
                    this.PlayedField = value;
                    this.RaisePropertyChanged("Played");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinaleDto", Namespace="http://schemas.datacontract.org/2004/07/SlimsteMens.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class FinaleDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Team1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Team1SecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Team2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Team2SecondsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team1 {
            get {
                return this.Team1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Team1Field, value) != true)) {
                    this.Team1Field = value;
                    this.RaisePropertyChanged("Team1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Team1Seconds {
            get {
                return this.Team1SecondsField;
            }
            set {
                if ((this.Team1SecondsField.Equals(value) != true)) {
                    this.Team1SecondsField = value;
                    this.RaisePropertyChanged("Team1Seconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team2 {
            get {
                return this.Team2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Team2Field, value) != true)) {
                    this.Team2Field = value;
                    this.RaisePropertyChanged("Team2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Team2Seconds {
            get {
                return this.Team2SecondsField;
            }
            set {
                if ((this.Team2SecondsField.Equals(value) != true)) {
                    this.Team2SecondsField = value;
                    this.RaisePropertyChanged("Team2Seconds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SlimsteAdminService.ISlimsteService", CallbackContract=typeof(SlimsteMens.Services.SlimsteAdminService.ISlimsteServiceCallback))]
    public interface ISlimsteService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/Start")]
        void Start(SlimsteMens.Services.SlimsteAdminService.GameDto game);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/Start")]
        System.Threading.Tasks.Task StartAsync(SlimsteMens.Services.SlimsteAdminService.GameDto game);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ResetGame")]
        void ResetGame(SlimsteMens.Services.SlimsteAdminService.ResetGameDto resetGameDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ResetGame")]
        System.Threading.Tasks.Task ResetGameAsync(SlimsteMens.Services.SlimsteAdminService.ResetGameDto resetGameDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/Subscribe", ReplyAction="http://tempuri.org/ISlimsteService/SubscribeResponse")]
        bool Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/Subscribe", ReplyAction="http://tempuri.org/ISlimsteService/SubscribeResponse")]
        System.Threading.Tasks.Task<bool> SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/Unsubscribe")]
        void Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/Unsubscribe")]
        System.Threading.Tasks.Task UnsubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartTimer")]
        void StartTimer();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartTimer")]
        System.Threading.Tasks.Task StartTimerAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StopTimer")]
        void StopTimer();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StopTimer")]
        System.Threading.Tasks.Task StopTimerAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextRound")]
        void NextRound();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextRound")]
        System.Threading.Tasks.Task NextRoundAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/SetTime")]
        void SetTime(SlimsteMens.Services.SlimsteAdminService.TurnTypeDto turn, int time);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/SetTime")]
        System.Threading.Tasks.Task SetTimeAsync(SlimsteMens.Services.SlimsteAdminService.TurnTypeDto turn, int time);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartRound369")]
        void StartRound369();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartRound369")]
        System.Threading.Tasks.Task StartRound369Async();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/Question369Incorrect")]
        void Question369Incorrect();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/Question369Incorrect")]
        System.Threading.Tasks.Task Question369IncorrectAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/Question369Correct")]
        void Question369Correct();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/Question369Correct")]
        System.Threading.Tasks.Task Question369CorrectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddQuestion369", ReplyAction="http://tempuri.org/ISlimsteService/AddQuestion369Response")]
        bool AddQuestion369(SlimsteMens.Services.SlimsteAdminService.ThreeSixNineQuestionDto questionDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddQuestion369", ReplyAction="http://tempuri.org/ISlimsteService/AddQuestion369Response")]
        System.Threading.Tasks.Task<bool> AddQuestion369Async(SlimsteMens.Services.SlimsteAdminService.ThreeSixNineQuestionDto questionDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartRoundPuzzle")]
        void StartRoundPuzzle();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartRoundPuzzle")]
        System.Threading.Tasks.Task StartRoundPuzzleAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextPuzzle")]
        void NextPuzzle();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextPuzzle")]
        System.Threading.Tasks.Task NextPuzzleAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ShowPuzzleAnswers")]
        void ShowPuzzleAnswers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ShowPuzzleAnswers")]
        System.Threading.Tasks.Task ShowPuzzleAnswersAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextTurnForPuzzle")]
        void NextTurnForPuzzle();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextTurnForPuzzle")]
        System.Threading.Tasks.Task NextTurnForPuzzleAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/QuestionPuzzleCorrect")]
        void QuestionPuzzleCorrect(long puzzleId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/QuestionPuzzleCorrect")]
        System.Threading.Tasks.Task QuestionPuzzleCorrectAsync(long puzzleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddPuzzleQuestion", ReplyAction="http://tempuri.org/ISlimsteService/AddPuzzleQuestionResponse")]
        bool AddPuzzleQuestion(SlimsteMens.Services.SlimsteAdminService.PuzzleQuestionDto puzzleQuestionDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddPuzzleQuestion", ReplyAction="http://tempuri.org/ISlimsteService/AddPuzzleQuestionResponse")]
        System.Threading.Tasks.Task<bool> AddPuzzleQuestionAsync(SlimsteMens.Services.SlimsteAdminService.PuzzleQuestionDto puzzleQuestionDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartRoundGallery")]
        void StartRoundGallery();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartRoundGallery")]
        System.Threading.Tasks.Task StartRoundGalleryAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextGallery")]
        void NextGallery();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextGallery")]
        System.Threading.Tasks.Task NextGalleryAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextTurnForGallery")]
        void NextTurnForGallery();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextTurnForGallery")]
        System.Threading.Tasks.Task NextTurnForGalleryAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/GalleryQuestionCorrect")]
        void GalleryQuestionCorrect();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/GalleryQuestionCorrect")]
        System.Threading.Tasks.Task GalleryQuestionCorrectAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/GalleryQuestionIncorrect")]
        void GalleryQuestionIncorrect();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/GalleryQuestionIncorrect")]
        System.Threading.Tasks.Task GalleryQuestionIncorrectAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ShowNextGalleryQuestionAnswer")]
        void ShowNextGalleryQuestionAnswer();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ShowNextGalleryQuestionAnswer")]
        System.Threading.Tasks.Task ShowNextGalleryQuestionAnswerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddGallery", ReplyAction="http://tempuri.org/ISlimsteService/AddGalleryResponse")]
        bool AddGallery(SlimsteMens.Services.SlimsteAdminService.GalleryDto gallery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddGallery", ReplyAction="http://tempuri.org/ISlimsteService/AddGalleryResponse")]
        System.Threading.Tasks.Task<bool> AddGalleryAsync(SlimsteMens.Services.SlimsteAdminService.GalleryDto gallery);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartRoundVideo")]
        void StartRoundVideo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartRoundVideo")]
        System.Threading.Tasks.Task StartRoundVideoAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextVideo")]
        void NextVideo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextVideo")]
        System.Threading.Tasks.Task NextVideoAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/PlayVideo")]
        void PlayVideo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/PlayVideo")]
        System.Threading.Tasks.Task PlayVideoAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/PlayVideoCompleted")]
        void PlayVideoCompleted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/PlayVideoCompleted")]
        System.Threading.Tasks.Task PlayVideoCompletedAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextTurnForVideo")]
        void NextTurnForVideo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextTurnForVideo")]
        System.Threading.Tasks.Task NextTurnForVideoAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/QuestionVideoCorrect")]
        void QuestionVideoCorrect(string answer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/QuestionVideoCorrect")]
        System.Threading.Tasks.Task QuestionVideoCorrectAsync(string answer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ShowVideoAnswers")]
        void ShowVideoAnswers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ShowVideoAnswers")]
        System.Threading.Tasks.Task ShowVideoAnswersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddVideo", ReplyAction="http://tempuri.org/ISlimsteService/AddVideoResponse")]
        bool AddVideo(SlimsteMens.Services.SlimsteAdminService.VideoDto video);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddVideo", ReplyAction="http://tempuri.org/ISlimsteService/AddVideoResponse")]
        System.Threading.Tasks.Task<bool> AddVideoAsync(SlimsteMens.Services.SlimsteAdminService.VideoDto video);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartFinale")]
        void StartFinale();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/StartFinale")]
        System.Threading.Tasks.Task StartFinaleAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextFinaleQuestion")]
        void NextFinaleQuestion();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextFinaleQuestion")]
        System.Threading.Tasks.Task NextFinaleQuestionAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ShowFinaleQuestionAnswers")]
        void ShowFinaleQuestionAnswers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/ShowFinaleQuestionAnswers")]
        System.Threading.Tasks.Task ShowFinaleQuestionAnswersAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextTurnForFinaleQuestion")]
        void NextTurnForFinaleQuestion();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/NextTurnForFinaleQuestion")]
        System.Threading.Tasks.Task NextTurnForFinaleQuestionAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/FinaleQuestionCorrect")]
        void FinaleQuestionCorrect(string answer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/FinaleQuestionCorrect")]
        System.Threading.Tasks.Task FinaleQuestionCorrectAsync(string answer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/SetTieBreakerWinner")]
        void SetTieBreakerWinner(System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.TurnTypeDto> winners);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/SetTieBreakerWinner")]
        System.Threading.Tasks.Task SetTieBreakerWinnerAsync(System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.TurnTypeDto> winners);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/SetFinaleTime")]
        void SetFinaleTime(SlimsteMens.Services.SlimsteAdminService.FinaleTurnTypeDto turn, int time);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/SetFinaleTime")]
        System.Threading.Tasks.Task SetFinaleTimeAsync(SlimsteMens.Services.SlimsteAdminService.FinaleTurnTypeDto turn, int time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddFinaleQuestion", ReplyAction="http://tempuri.org/ISlimsteService/AddFinaleQuestionResponse")]
        bool AddFinaleQuestion(SlimsteMens.Services.SlimsteAdminService.FinaleQuestionDto finaleDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlimsteService/AddFinaleQuestion", ReplyAction="http://tempuri.org/ISlimsteService/AddFinaleQuestionResponse")]
        System.Threading.Tasks.Task<bool> AddFinaleQuestionAsync(SlimsteMens.Services.SlimsteAdminService.FinaleQuestionDto finaleDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISlimsteServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnGameStarted")]
        void OnGameStarted(SlimsteMens.Services.SlimsteAdminService.GameDto game);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnFinaleStarted")]
        void OnFinaleStarted(SlimsteMens.Services.SlimsteAdminService.FinaleDto finale);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnSetTimer")]
        void OnSetTimer(SlimsteMens.Services.SlimsteAdminService.TurnTypeDto turn, int seconds);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnSetTimerFinale")]
        void OnSetTimerFinale(SlimsteMens.Services.SlimsteAdminService.FinaleTurnTypeDto turn, int seconds);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnTurnChange")]
        void OnTurnChange(SlimsteMens.Services.SlimsteAdminService.TurnTypeDto turn);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnFinaleTurnChange")]
        void OnFinaleTurnChange(SlimsteMens.Services.SlimsteAdminService.FinaleTurnTypeDto turn);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnStartRound369")]
        void OnStartRound369();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnQuestion369")]
        void OnQuestion369(SlimsteMens.Services.SlimsteAdminService.ThreeSixNineQuestionDto question);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnEndRound369")]
        void OnEndRound369();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnStartRoundPuzzle")]
        void OnStartRoundPuzzle();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnQuestionPuzzle")]
        void OnQuestionPuzzle(System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.PuzzleQuestionDto> puzzle);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnPuzzleCorrect")]
        void OnPuzzleCorrect(long puzzleId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnQuestionPuzzleCompleted")]
        void OnQuestionPuzzleCompleted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnShowPuzzleAnswers")]
        void OnShowPuzzleAnswers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnEndRoundPuzzle")]
        void OnEndRoundPuzzle();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnStartRoundGallery")]
        void OnStartRoundGallery();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnNextGalleryQuestion")]
        void OnNextGalleryQuestion();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnGalleryCompleted")]
        void OnGalleryCompleted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnQuestionGallery")]
        void OnQuestionGallery(SlimsteMens.Services.SlimsteAdminService.GalleryDto galleryDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnShowGalleryAnswer")]
        void OnShowGalleryAnswer();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnEndRoundGallery")]
        void OnEndRoundGallery();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnStartRoundVideo")]
        void OnStartRoundVideo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnQuestionVideo")]
        void OnQuestionVideo(SlimsteMens.Services.SlimsteAdminService.VideoDto videoDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnPlayVideo")]
        void OnPlayVideo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnPlayVideoCompleted")]
        void OnPlayVideoCompleted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnVideoQuestionCorrect")]
        void OnVideoQuestionCorrect(string answer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnVideoCompleted")]
        void OnVideoCompleted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnShowVideoAnswers")]
        void OnShowVideoAnswers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnEndRoundVideo")]
        void OnEndRoundVideo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnTiebreakerQuestion")]
        void OnTiebreakerQuestion(System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.TurnTypeDto> players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnFinaleQuestion")]
        void OnFinaleQuestion(SlimsteMens.Services.SlimsteAdminService.FinaleQuestionDto finaleQuestionDto);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnFinaleQuestionCompleted")]
        void OnFinaleQuestionCompleted();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnShowFinaleQuestionAnswers")]
        void OnShowFinaleQuestionAnswers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnFinaleAnswerCorrect")]
        void OnFinaleAnswerCorrect(string answer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISlimsteService/OnGameWon")]
        void OnGameWon(string winner);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISlimsteServiceChannel : SlimsteMens.Services.SlimsteAdminService.ISlimsteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SlimsteServiceClient : System.ServiceModel.DuplexClientBase<SlimsteMens.Services.SlimsteAdminService.ISlimsteService>, SlimsteMens.Services.SlimsteAdminService.ISlimsteService {
        
        public SlimsteServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SlimsteServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SlimsteServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SlimsteServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SlimsteServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Start(SlimsteMens.Services.SlimsteAdminService.GameDto game) {
            base.Channel.Start(game);
        }
        
        public System.Threading.Tasks.Task StartAsync(SlimsteMens.Services.SlimsteAdminService.GameDto game) {
            return base.Channel.StartAsync(game);
        }
        
        public void ResetGame(SlimsteMens.Services.SlimsteAdminService.ResetGameDto resetGameDto) {
            base.Channel.ResetGame(resetGameDto);
        }
        
        public System.Threading.Tasks.Task ResetGameAsync(SlimsteMens.Services.SlimsteAdminService.ResetGameDto resetGameDto) {
            return base.Channel.ResetGameAsync(resetGameDto);
        }
        
        public bool Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync() {
            return base.Channel.UnsubscribeAsync();
        }
        
        public void StartTimer() {
            base.Channel.StartTimer();
        }
        
        public System.Threading.Tasks.Task StartTimerAsync() {
            return base.Channel.StartTimerAsync();
        }
        
        public void StopTimer() {
            base.Channel.StopTimer();
        }
        
        public System.Threading.Tasks.Task StopTimerAsync() {
            return base.Channel.StopTimerAsync();
        }
        
        public void NextRound() {
            base.Channel.NextRound();
        }
        
        public System.Threading.Tasks.Task NextRoundAsync() {
            return base.Channel.NextRoundAsync();
        }
        
        public void SetTime(SlimsteMens.Services.SlimsteAdminService.TurnTypeDto turn, int time) {
            base.Channel.SetTime(turn, time);
        }
        
        public System.Threading.Tasks.Task SetTimeAsync(SlimsteMens.Services.SlimsteAdminService.TurnTypeDto turn, int time) {
            return base.Channel.SetTimeAsync(turn, time);
        }
        
        public void StartRound369() {
            base.Channel.StartRound369();
        }
        
        public System.Threading.Tasks.Task StartRound369Async() {
            return base.Channel.StartRound369Async();
        }
        
        public void Question369Incorrect() {
            base.Channel.Question369Incorrect();
        }
        
        public System.Threading.Tasks.Task Question369IncorrectAsync() {
            return base.Channel.Question369IncorrectAsync();
        }
        
        public void Question369Correct() {
            base.Channel.Question369Correct();
        }
        
        public System.Threading.Tasks.Task Question369CorrectAsync() {
            return base.Channel.Question369CorrectAsync();
        }
        
        public bool AddQuestion369(SlimsteMens.Services.SlimsteAdminService.ThreeSixNineQuestionDto questionDto) {
            return base.Channel.AddQuestion369(questionDto);
        }
        
        public System.Threading.Tasks.Task<bool> AddQuestion369Async(SlimsteMens.Services.SlimsteAdminService.ThreeSixNineQuestionDto questionDto) {
            return base.Channel.AddQuestion369Async(questionDto);
        }
        
        public void StartRoundPuzzle() {
            base.Channel.StartRoundPuzzle();
        }
        
        public System.Threading.Tasks.Task StartRoundPuzzleAsync() {
            return base.Channel.StartRoundPuzzleAsync();
        }
        
        public void NextPuzzle() {
            base.Channel.NextPuzzle();
        }
        
        public System.Threading.Tasks.Task NextPuzzleAsync() {
            return base.Channel.NextPuzzleAsync();
        }
        
        public void ShowPuzzleAnswers() {
            base.Channel.ShowPuzzleAnswers();
        }
        
        public System.Threading.Tasks.Task ShowPuzzleAnswersAsync() {
            return base.Channel.ShowPuzzleAnswersAsync();
        }
        
        public void NextTurnForPuzzle() {
            base.Channel.NextTurnForPuzzle();
        }
        
        public System.Threading.Tasks.Task NextTurnForPuzzleAsync() {
            return base.Channel.NextTurnForPuzzleAsync();
        }
        
        public void QuestionPuzzleCorrect(long puzzleId) {
            base.Channel.QuestionPuzzleCorrect(puzzleId);
        }
        
        public System.Threading.Tasks.Task QuestionPuzzleCorrectAsync(long puzzleId) {
            return base.Channel.QuestionPuzzleCorrectAsync(puzzleId);
        }
        
        public bool AddPuzzleQuestion(SlimsteMens.Services.SlimsteAdminService.PuzzleQuestionDto puzzleQuestionDto) {
            return base.Channel.AddPuzzleQuestion(puzzleQuestionDto);
        }
        
        public System.Threading.Tasks.Task<bool> AddPuzzleQuestionAsync(SlimsteMens.Services.SlimsteAdminService.PuzzleQuestionDto puzzleQuestionDto) {
            return base.Channel.AddPuzzleQuestionAsync(puzzleQuestionDto);
        }
        
        public void StartRoundGallery() {
            base.Channel.StartRoundGallery();
        }
        
        public System.Threading.Tasks.Task StartRoundGalleryAsync() {
            return base.Channel.StartRoundGalleryAsync();
        }
        
        public void NextGallery() {
            base.Channel.NextGallery();
        }
        
        public System.Threading.Tasks.Task NextGalleryAsync() {
            return base.Channel.NextGalleryAsync();
        }
        
        public void NextTurnForGallery() {
            base.Channel.NextTurnForGallery();
        }
        
        public System.Threading.Tasks.Task NextTurnForGalleryAsync() {
            return base.Channel.NextTurnForGalleryAsync();
        }
        
        public void GalleryQuestionCorrect() {
            base.Channel.GalleryQuestionCorrect();
        }
        
        public System.Threading.Tasks.Task GalleryQuestionCorrectAsync() {
            return base.Channel.GalleryQuestionCorrectAsync();
        }
        
        public void GalleryQuestionIncorrect() {
            base.Channel.GalleryQuestionIncorrect();
        }
        
        public System.Threading.Tasks.Task GalleryQuestionIncorrectAsync() {
            return base.Channel.GalleryQuestionIncorrectAsync();
        }
        
        public void ShowNextGalleryQuestionAnswer() {
            base.Channel.ShowNextGalleryQuestionAnswer();
        }
        
        public System.Threading.Tasks.Task ShowNextGalleryQuestionAnswerAsync() {
            return base.Channel.ShowNextGalleryQuestionAnswerAsync();
        }
        
        public bool AddGallery(SlimsteMens.Services.SlimsteAdminService.GalleryDto gallery) {
            return base.Channel.AddGallery(gallery);
        }
        
        public System.Threading.Tasks.Task<bool> AddGalleryAsync(SlimsteMens.Services.SlimsteAdminService.GalleryDto gallery) {
            return base.Channel.AddGalleryAsync(gallery);
        }
        
        public void StartRoundVideo() {
            base.Channel.StartRoundVideo();
        }
        
        public System.Threading.Tasks.Task StartRoundVideoAsync() {
            return base.Channel.StartRoundVideoAsync();
        }
        
        public void NextVideo() {
            base.Channel.NextVideo();
        }
        
        public System.Threading.Tasks.Task NextVideoAsync() {
            return base.Channel.NextVideoAsync();
        }
        
        public void PlayVideo() {
            base.Channel.PlayVideo();
        }
        
        public System.Threading.Tasks.Task PlayVideoAsync() {
            return base.Channel.PlayVideoAsync();
        }
        
        public void PlayVideoCompleted() {
            base.Channel.PlayVideoCompleted();
        }
        
        public System.Threading.Tasks.Task PlayVideoCompletedAsync() {
            return base.Channel.PlayVideoCompletedAsync();
        }
        
        public void NextTurnForVideo() {
            base.Channel.NextTurnForVideo();
        }
        
        public System.Threading.Tasks.Task NextTurnForVideoAsync() {
            return base.Channel.NextTurnForVideoAsync();
        }
        
        public void QuestionVideoCorrect(string answer) {
            base.Channel.QuestionVideoCorrect(answer);
        }
        
        public System.Threading.Tasks.Task QuestionVideoCorrectAsync(string answer) {
            return base.Channel.QuestionVideoCorrectAsync(answer);
        }
        
        public void ShowVideoAnswers() {
            base.Channel.ShowVideoAnswers();
        }
        
        public System.Threading.Tasks.Task ShowVideoAnswersAsync() {
            return base.Channel.ShowVideoAnswersAsync();
        }
        
        public bool AddVideo(SlimsteMens.Services.SlimsteAdminService.VideoDto video) {
            return base.Channel.AddVideo(video);
        }
        
        public System.Threading.Tasks.Task<bool> AddVideoAsync(SlimsteMens.Services.SlimsteAdminService.VideoDto video) {
            return base.Channel.AddVideoAsync(video);
        }
        
        public void StartFinale() {
            base.Channel.StartFinale();
        }
        
        public System.Threading.Tasks.Task StartFinaleAsync() {
            return base.Channel.StartFinaleAsync();
        }
        
        public void NextFinaleQuestion() {
            base.Channel.NextFinaleQuestion();
        }
        
        public System.Threading.Tasks.Task NextFinaleQuestionAsync() {
            return base.Channel.NextFinaleQuestionAsync();
        }
        
        public void ShowFinaleQuestionAnswers() {
            base.Channel.ShowFinaleQuestionAnswers();
        }
        
        public System.Threading.Tasks.Task ShowFinaleQuestionAnswersAsync() {
            return base.Channel.ShowFinaleQuestionAnswersAsync();
        }
        
        public void NextTurnForFinaleQuestion() {
            base.Channel.NextTurnForFinaleQuestion();
        }
        
        public System.Threading.Tasks.Task NextTurnForFinaleQuestionAsync() {
            return base.Channel.NextTurnForFinaleQuestionAsync();
        }
        
        public void FinaleQuestionCorrect(string answer) {
            base.Channel.FinaleQuestionCorrect(answer);
        }
        
        public System.Threading.Tasks.Task FinaleQuestionCorrectAsync(string answer) {
            return base.Channel.FinaleQuestionCorrectAsync(answer);
        }
        
        public void SetTieBreakerWinner(System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.TurnTypeDto> winners) {
            base.Channel.SetTieBreakerWinner(winners);
        }
        
        public System.Threading.Tasks.Task SetTieBreakerWinnerAsync(System.Collections.Generic.List<SlimsteMens.Services.SlimsteAdminService.TurnTypeDto> winners) {
            return base.Channel.SetTieBreakerWinnerAsync(winners);
        }
        
        public void SetFinaleTime(SlimsteMens.Services.SlimsteAdminService.FinaleTurnTypeDto turn, int time) {
            base.Channel.SetFinaleTime(turn, time);
        }
        
        public System.Threading.Tasks.Task SetFinaleTimeAsync(SlimsteMens.Services.SlimsteAdminService.FinaleTurnTypeDto turn, int time) {
            return base.Channel.SetFinaleTimeAsync(turn, time);
        }
        
        public bool AddFinaleQuestion(SlimsteMens.Services.SlimsteAdminService.FinaleQuestionDto finaleDto) {
            return base.Channel.AddFinaleQuestion(finaleDto);
        }
        
        public System.Threading.Tasks.Task<bool> AddFinaleQuestionAsync(SlimsteMens.Services.SlimsteAdminService.FinaleQuestionDto finaleDto) {
            return base.Channel.AddFinaleQuestionAsync(finaleDto);
        }
    }
}
