// <auto-generated />
namespace SlimsteMens.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddColumnPlayedToFinaleQuestions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumnPlayedToFinaleQuestions));
        
        string IMigrationMetadata.Id
        {
            get { return "201210300516543_AddColumnPlayedToFinaleQuestions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
